### PR TITLE
Add extensions to postgres DB to allow for database import

### PR DESCRIPTION
**Pull request by SillyInventor**
Add adminpack, postgis, and postgis_topology extensions to csdt.yml

### CODE REVIEW

**Comment by SillyInventor** [comment]
@joshuacherry this should be what is required to allow for a complete database transfer. I didn't include the call for the import itself because I don't know how you want to handle that.

**Comment by joshuacherry** [comment]
Since the goal is to eventually have the database automatically import from production to dev periodically, I want to use [Ansible's Cron Module](http://docs.ansible.com/ansible/cron_module.html) to setup the script. 
  
This way it is dynamic enough that external users of this role do not need to make modifications to the tasks and/or templates, just variables.

**Comment by SillyInventor** [comment]
I don't really know ansible, but are you thinking something like:

```
  name: Creates weekly backup
  cron: minute="59" hour="23" weekday="fri"
        name: "Scheduled backup"
        cron_file: "postgresbackup"
        user: postgres
        job: "{{csdt_django_git_destination}}"/postgresbackup.sh
  name: Importing database
        sudo_user: postgres
        shell: psql "{{ csdt_django_secret_db }}" < "{{csdt_django_git_destination}}"/database.sql
  name: Grant table permissions
        sudo_user: postgres
        postgresql_privs: database="{{csdt_django_secret_user}}" schema=dictionary state=present privs=SELECT,INSERT,UPDATE type=table roles="{{csdt_django_secret_user}}" grant_option=no objs=ALL_IN_SCHEMA
  name: Grant sequence permissions
        sudo_user: postgres
        postgresql_privs: database="{{csdt_django_secret_db}}" schema=dictionary state=present privs=SELECT,INSERT,UPDATE type=sequence roles="{{csdt_django_secret_user}}" grant_option=no objs=ALL_IN_SCHEMA
```

postgresbackup.sh would look like:
```shell
sudo su postgres -c "pg_dump -c csdt > database.sql"
cp database.sql # add location
cp media # add location
```

**Comment by joshuacherry** [comment]
Something similar, mainly the cron entry, creation of backup script, and maybe the privileges would remain in the playbook since those are easily idempotent. The script that cron runs would be created with a template so that future changes can be managed easily, I also plan to have the script backup the production database remotely then import the DB into dev so I won't have any manual work to do on the server with copying of files.

**Comment by SillyInventor** [comment]
Closed in favor of #2

**Pull request closed without merging**
